version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - 8000:8000
    networks:
      - app_network

  # frontend:
  #   container_name: frontend
  #   depends_on:
  #     - backend
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   restart: always
  #   environment:
  #     - VITE_API_URL=http://localhost:8000
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - project

networks:
  app_network: